import { NgModule } from '@angular/core';
import { MatToolbarModule, MatTooltipModule, MatIconModule, MatSidenavModule, MatTabsModule, MatFormFieldModule, MatProgressSpinnerModule, MatCommonModule, 
  MatRippleModule, MatButtonModule, MatCheckboxModule, MatSelectModule, MatSliderModule, MatListModule, MatCardModule, MatChipsModule, MatProgressBarModule, 
  MatInputModule, MatSnackBarModule, MatMenuModule, MatDialogModule, MatAutocompleteModule, MatDatepickerModule, MatExpansionModule, MatTableModule, 
  MatPaginatorModule, MatNativeDateModule, MatSlideToggleModule, MatRadioModule } from '@angular/material';

@NgModule({
  imports: [
    MatProgressSpinnerModule,
    MatCommonModule,
    MatRippleModule,
    MatButtonModule,
    MatCheckboxModule,
    MatSelectModule,
    MatSliderModule,
    MatSidenavModule,
    MatListModule,
    MatCardModule,
    MatChipsModule,
    MatIconModule,
    MatProgressBarModule,
    MatInputModule,
    MatSnackBarModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatMenuModule,
    MatDialogModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatExpansionModule,
    MatTableModule,
    MatPaginatorModule,
    MatFormFieldModule,
    MatNativeDateModule,
    MatSlideToggleModule,
    MatRadioModule
  ],
  exports: [
    MatProgressSpinnerModule,
    MatCommonModule,
    MatRippleModule,
    MatButtonModule,
    MatCheckboxModule,
    MatSelectModule,
    MatSliderModule,
    MatSidenavModule,
    MatListModule,
    MatCardModule,
    MatChipsModule,
    MatIconModule,
    MatProgressBarModule,
    MatInputModule,
    MatSnackBarModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatMenuModule,
    MatDialogModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatExpansionModule,
    MatTableModule,
    MatPaginatorModule,
    MatFormFieldModule,
    MatNativeDateModule,
    MatSlideToggleModule,
    MatRadioModule
  ],
  declarations: []
})
export class MeloaMaterialModule { }
